// <auto-generated />
using Characters.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Characters.Dal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220501193237_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Characters.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<bool>("isAlive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 75,
                            ImageUrl = "https://static.wikia.nocookie.net/ortadunya/images/3/34/Aragorn2.jpg/revision/latest?cb=20210609105006",
                            Name = "Aragorn",
                            RaceId = 2,
                            isAlive = true
                        },
                        new
                        {
                            Id = 2,
                            Age = 150,
                            ImageUrl = "https://static.wikia.nocookie.net/lotr/images/e/e7/Gandalf_the_Grey.jpg/revision/latest?cb=20121110131754",
                            Name = "Gandalf",
                            RaceId = 8,
                            isAlive = true
                        },
                        new
                        {
                            Id = 3,
                            Age = 43,
                            ImageUrl = "https://static.wikia.nocookie.net/lotr/images/b/b4/Seanbean_boromir.jpg/revision/latest?cb=20110327195115",
                            Name = "Boromir",
                            RaceId = 2,
                            isAlive = false
                        },
                        new
                        {
                            Id = 4,
                            Age = 66,
                            ImageUrl = "https://static.wikia.nocookie.net/middle-earth-film-saga/images/7/77/Legolas.png/revision/latest/top-crop/width/360/height/450?cb=20160207050831",
                            Name = "Legolas",
                            RaceId = 1,
                            isAlive = true
                        },
                        new
                        {
                            Id = 5,
                            Age = 135,
                            ImageUrl = "https://static.wikia.nocookie.net/lotr/images/5/59/Witch-king.jpg/revision/latest?cb=20220209185252",
                            Name = "Witch King",
                            RaceId = 2,
                            isAlive = false
                        },
                        new
                        {
                            Id = 6,
                            Age = 63,
                            ImageUrl = "https://static.wikia.nocookie.net/ortadunya/images/4/43/Gimli.jpg/revision/latest/top-crop/width/360/height/450?cb=20190424060619",
                            Name = "Gimli",
                            RaceId = 3,
                            isAlive = true
                        },
                        new
                        {
                            Id = 7,
                            Age = 200,
                            ImageUrl = "https://static.wikia.nocookie.net/ortadunya/images/0/06/Gilgalad.jpg/revision/latest/top-crop/width/360/height/450?cb=20190628103851",
                            Name = "Gil-Galad",
                            RaceId = 1,
                            isAlive = true
                        },
                        new
                        {
                            Id = 8,
                            Age = 150,
                            ImageUrl = "https://static.wikia.nocookie.net/lotr/images/0/0c/Christopher_Lee_as_Saruman.jpg/revision/latest/top-crop/width/360/height/360?cb=20170127113833",
                            Name = "Saruman",
                            RaceId = 8,
                            isAlive = false
                        });
                });

            modelBuilder.Entity("Characters.Entities.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Elves"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Men"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dwarves"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Hobbits"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Orcs"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Ents"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Maiar"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Trolls"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Barrow-wights"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Balrogs"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Dragons"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Easterlings"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Valar"
                        });
                });

            modelBuilder.Entity("Characters.Entities.Character", b =>
                {
                    b.HasOne("Characters.Entities.Race", "Race")
                        .WithMany("Characters")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Characters.Entities.Race", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
