USE [master]
GO

/****** Object:  Database [RentDb]    Script Date: 26.05.2022 21:29:46 ******/
CREATE DATABASE [RentDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RentDb', FILENAME = N'C:\Users\Burak\RentDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RentDb_log', FILENAME = N'C:\Users\Burak\RentDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RentDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RentDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RentDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RentDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RentDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RentDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [RentDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RentDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RentDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RentDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RentDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RentDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RentDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RentDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RentDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RentDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RentDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RentDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RentDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RentDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RentDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RentDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RentDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RentDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RentDb] SET  MULTI_USER 
GO

ALTER DATABASE [RentDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RentDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RentDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RentDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RentDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RentDb] SET QUERY_STORE = OFF
GO

USE [RentDb]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [RentDb] SET  READ_WRITE 
GO

