// <auto-generated />
using System;
using BookCategory.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookCategory.DataAccess.Migrations
{
    [DbContext(typeof(BookCategoryDbContext))]
    [Migration("20220516104239_initialize")]
    partial class initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BookCategory.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CategoryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Page")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookName = "Küçük Prens",
                            CategoryId = 1,
                            IsActive = true,
                            Page = 110
                        },
                        new
                        {
                            Id = 2,
                            BookName = "Simyacı",
                            CategoryId = 2,
                            IsActive = true,
                            Page = 112
                        },
                        new
                        {
                            Id = 3,
                            BookName = "Homo Deus",
                            CategoryId = 3,
                            IsActive = true,
                            Page = 160
                        },
                        new
                        {
                            Id = 4,
                            BookName = "İnsan Geleceğini Nasıl Kurar?",
                            CategoryId = 4,
                            IsActive = true,
                            Page = 120
                        });
                });

            modelBuilder.Entity("BookCategory.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Çocuk Kitabı"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Edebiyat Roman"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tarih"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kişisel Gelişim"
                        });
                });

            modelBuilder.Entity("BookCategory.Entities.Book", b =>
                {
                    b.HasOne("BookCategory.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BookCategory.Entities.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
